---
- name: Prepare docker host for running containers
  hosts: docker_host
  become: true
  roles:
    - role: installDocker
      tags: [install]

    - role: createInfra
      tags: [infra]

- name: Install and configure nginx
  hosts: nginx
  become: true
  roles:
    - installNginx

- name: Configure Nginx webserver
  hosts: nginx_web
  become: true
  roles:
    - configureNginxWebserver

- name: Configure Nginx webserver
  hosts: nginx_rproxy
  become: true
  roles:
    - configureNginxRProxy

- name: Install and configure Prometheus
  hosts: prometheus
  become: true
  roles:
    - role: installAndConfigurePrometheus
      tags: prom

- name: Install and configure Elasticsearch
  hosts: elastic
  become: true
  roles:
    - role: installElastic
      tags: elk

- name: Install daemontools and configure custom service
  hosts: prometheus
  become: true
  roles:
    - role: installDaemon
      tags: daemon
