---
- name: Update apt cache
  apt:
    cache_valid_time: 3600
    update_cache: true

- name: Install GPG and Curl
  apt:
    pkg:
      - gnupg
      - apt-transport-https
      - curl

- name: Add Elastic GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4

- name: Add Elastic apt repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: Install elasticsearch and prometheus exporters
  apt:
    pkg:
      - apt-transport-https
      - elasticsearch
      - prometheus-node-exporter
      - prometheus-elasticsearch-exporter
    update_cache: true

- name: Configure Elastic with elasticsearch.yml
  template:
      src: elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart_elastic

- name: Start Elasticsearch
  service:
      name: elasticsearch
      state: started
  ignore_errors: true

- name: Start prometheus-elasticsearch-exporter
  service:
      name: prometheus-elasticsearch-exporter
      state: started
  ignore_errors: true

- name: Start prometheus-node-exporter
  service:
      name: prometheus-node-exporter
      state: started
  ignore_errors: true

- name: Wait for Elastic to started
  wait_for:
    port: 9200
    state: started
    host: "{{ inventory_hostname }}"

- name: Create my_index and set replicas
  command: |
    curl -X PUT "{{ inventory_hostname }}:9200/my-index?pretty" -H 'Content-Type: application/json' -d'
    {
      "settings": {
        "index": {
          "number_of_shards": 3,  
          "number_of_replicas": 2 
        }
      }
    }
    '
