---
- name: Update apt cache
  apt:
    cache_valid_time: 3600
    update_cache: true

- name: Install daemontools
  apt:
    pkg:
      - python3-requests
      - daemontools
      - daemontools-run

- name: Copy python script
  copy:
    src: statusChecker.py
    dest: /root/customService/

- name: Copy run script
  copy:
    src: run
    dest: /root/customService/
    mode: '0755'

- name: Link service to the /etc/service
  file:
    src: /root/customService/
    dest: /etc/service/customService
    state: link

- name: Start svscanboot
  shell: nohup svscanboot &
  poll: 0
