---
- name: Create own docker network
  docker_network:
    name: my_network
    ipam_config:
      - subnet: "192.168.0.0/24"
        gateway: "192.168.0.1"
        iprange: "192.168.0.0/25"
    state: present

- name: Copy ssh key
  copy:
    src: containers_key.pub
    dest: /srv/ssh_key.pub
    mode: 0644

- name: Build generic docker image
  docker_image:
    name: generic_img
    source: build
    build:
      path: ./docker/
      pull: true
      dockerfile: ./Dockerfile
    state: present

- name: Set vm.max_map_count
  shell: sysctl -w vm.max_map_count=262144

- name: Create containers
  docker_container:
    name: "{{ item.name }}"
    restart_policy: always
    image: generic_img:latest
    volumes:
      - /srv/ssh_key.pub:/root/.ssh/authorized_keys
    networks:
      - name: my_network
        ipv4_address: "{{ item.ip }}"
    published_ports:
      "{{ item.ports }}"
    detach: true
  with_items:
    - {name: prometheus, ip: "192.168.0.2", ports: ["9090:9090", "9093:9093", "2202:22/tcp"]}
    - {name: nginx_webserver, ip: "192.168.0.3", ports: ["2203:22/tcp"]}
    - {name: nginx_rproxy, ip: "192.168.0.4", ports: ["2204:22/tcp", "80:80", "443:443"]}

- name: Create Elasticsearch containers
  docker_container:
    name: "{{ item.name }}"
    restart_policy: always
    image: generic_img:latest
    volumes:
      - /srv/ssh_key.pub:/root/.ssh/authorized_keys
    networks:
      - name: my_network
        ipv4_address: "{{ item.ip }}"
    published_ports:
      "{{ item.ports }}"
    detach: true
    env:
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m
    memory: 2G
  with_items:
    - {name: es1, ip: "192.168.0.5", ports: ["9205:9200"]}
    - {name: es2, ip: "192.168.0.6", ports: ["9206:9200"]}
    - {name: es3, ip: "192.168.0.7", ports: ["9207:9200"]}
    - {name: es4, ip: "192.168.0.8", ports: ["9208:9200"]}
    - {name: es5, ip: "192.168.0.9", ports: ["9209:9200"]}
