---
- name: Update apt cache
  apt:
    cache_valid_time: 3600
    update_cache: true

- name: Install prometheus
  apt:
    pkg: 
      - prometheus
      - python3-requests
    state: present

- name: Copy prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: 0644
  notify: restart_prometheus

- name: Start Prometheus
  service:
      name: prometheus
      state: started
  ignore_errors: true

- name: Start prometheus-node-exporter
  service:
      name: prometheus-node-exporter
      state: started
  ignore_errors: true